
name: Scheduled Trading Bot

on:
  schedule:
    - cron: "30 12 * * 1-5"  # 5:30 AM PT
    - cron: "30 20 * * 1-5"  # 1:30 PM PT
  workflow_dispatch:

jobs:
  trade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run trading script
        env:
          TRADING_ENV: ${{ secrets.TRADING_ENV }}
          APCA_API_KEY_ID: ${{ secrets['PKOZ1KULBUMRJZUPRVJG' + secrets.TRADING_ENV] }}
          APCA_API_SECRET_KEY: ${{ secrets['G0EaYtsDmZwY8RHogivfGHGmA4oKNxT9dQx4aG6K' + secrets.TRADING_ENV] }}
          APCA_API_BASE_URL: ${{ secrets['https://paper-api.alpaca.markets' + secrets.TRADING_ENV] }}
        run: python main.py
