name: Run Auto Trading

on:
  schedule:
    - cron: '30 13 * * 1-5'  # Weekdays at 13:30 UTC
  workflow_dispatch:

jobs:
  run-trader:
    runs-on: ubuntu-latest

    env:
      TRADING_ENV: PAPER
      APCA_API_KEY_ID_PAPER: ${{ secrets.APCA_API_KEY_ID_PAPER }}
      APCA_API_SECRET_KEY_PAPER: ${{ secrets.APCA_API_SECRET_KEY_PAPER }}
      APCA_API_BASE_URL_PAPER: ${{ secrets.APCA_API_BASE_URL_PAPER }}
      APCA_API_KEY_ID_LIVE: ${{ secrets.APCA_API_KEY_ID_LIVE }}
      APCA_API_SECRET_KEY_LIVE: ${{ secrets.APCA_API_SECRET_KEY_LIVE }}
      APCA_API_BASE_URL_LIVE: ${{ secrets.APCA_API_BASE_URL_LIVE }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run trading strategy
        run: python main.py

           - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: GitHub Actions - Trade Execution Status: ${{ job.status }}
          body: |
            The trading workflow has completed with status: ${{ job.status }}.
            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Run ID: ${{ github.run_id }}
          to: ${{ secrets.EMAIL_RECIPIENT }}
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>